### ISSUE TITLE
Device timeout and app crash

### ISSUE THREAD

**Issue by rhannink** [amstelzone/com.amstelzone.dru#1]
Hello,

Just tried your new app. Adding a new device is working (fixen IP Address), but the it retries to Connect to the device, then I get a timeout off the new device and then the app crashes.

I Think you need to include some more NodeJS packages.........

```
─────────────── Logging stdout & stderr ───────────────
2020-06-01 14:18:50 [log] [DruModbusApp] Initializing Dru Modbus app ...
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'debug'
Require stack:
- /node_modules/jsmodbus/src/modbus-client.js
- /node_modules/jsmodbus/src/modbus-tcp-client.js
- /node_modules/jsmodbus/src/modbus.js
- /drivers/dru/device.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:191)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/jsmodbus/src/modbus-client.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/jsmodbus/src/modbus-client.js',
    '/node_modules/jsmodbus/src/modbus-tcp-client.js',
    '/node_modules/jsmodbus/src/modbus.js',
    '/drivers/dru/device.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js'
  ]
}

--- INFO: com.amstelzone.dru has been killed ---
```

Gr. Remco

**Comment by amstelzone** [comment]
Added the modules to GitHub package.
