### ISSUE TITLE
Error when adding a new device

### ISSUE THREAD

**Issue by nickklomp** [amstelzone/com.amstelzone.dru#4]
Added my Dru maestro. Once I click the icon on homey the app crashes. Stacktrace can be found below.

Thanks

— Profile your app's performance at https://go.athom.com/app-profiling?homey=5da5d0068b238e0c654d4e91&app=com.amstelzone.dru
─────────────── Logging stdout & stderr ───────────────
2021-02-19 09:34:09 [log] [DruModbusApp] Initializing Dru Modbus app ...
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'debug'
Require stack:
- /node_modules/jsmodbus/src/modbus-client.js
- /node_modules/jsmodbus/src/modbus-tcp-client.js
- /node_modules/jsmodbus/src/modbus.js
- /drivers/dru/device.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:191)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/jsmodbus/src/modbus-client.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/jsmodbus/src/modbus-client.js',
    '/node_modules/jsmodbus/src/modbus-tcp-client.js',
    '/node_modules/jsmodbus/src/modbus.js',
    '/drivers/dru/device.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/Driver.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap/bootstrap.js'
  ]
}

--- INFO: com.amstelzone.dru has been killed ---

**Comment by nickklomp** [comment]
Found the issue. Debug module is missing in the package. After a npm install it is working great for me! Thanks for this nice app
